name: Deploy Portfolio Site

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_PORT }}
          script: |
            cd ~/GitRepos/portfolio-site-stevenBorkowskiDev
            git pull origin main